name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: nure_cli.zip
        path: /home/runner/work/nure_cli/nure_cli/target/release/nure_cli
